// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sim_Card_Managment.data;

#nullable disable

namespace Sim_Card_Management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809102442_edite-group")]
    partial class editegroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sim_Card_Management.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("VpnOverInternetStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.DeviceSerialOperation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("NetworkTypeChange")
                        .HasColumnType("bit");

                    b.Property<string>("NewSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OperationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SimId");

                    b.ToTable("DeviceSerialOperations");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.DeviceStatusType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceStatusesType");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.DocumentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("DocumentDetails");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.InternetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bandwidth")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("QuotaGB")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("RenewalDay")
                        .HasColumnType("int");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("SimId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("SimId");

                    b.ToTable("InternetLines");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.VpnConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("ConnectionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("LineSpeed")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ConnectionTypeId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("VpnConnections");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.VpnConnectionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("VpnConnectionTypes");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformedBy")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedBy");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReplacedBySimId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplacedByUsbId")
                        .HasColumnType("int");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int");

                    b.Property<int?>("SimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("UsbId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedBySimId");

                    b.HasIndex("ReplacedByUsbId");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("SimId");

                    b.HasIndex("StatusTypeId");

                    b.HasIndex("UsbId");

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("FromSubscriptionId")
                        .HasColumnType("int");

                    b.Property<int?>("NewSubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SimId")
                        .HasColumnType("int");

                    b.Property<int>("ToEmpId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsbId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromSubscriptionId");

                    b.HasIndex("NewSubscriptionId");

                    b.HasIndex("SimId");

                    b.HasIndex("ToEmpId");

                    b.HasIndex("UsbId");

                    b.ToTable("DeviceTransfers");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DocumenttypeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("SignatureData")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SignatureType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumenttypeId");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NationalID")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.GroupPermission", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("GroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("GroupPermissions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.NonEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("NonEmployees");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Quota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ExtraAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Quotas");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.ReceiverSignature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SignatureData")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SignatureType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SignedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SignedBy");

                    b.HasIndex("SubscriptionId")
                        .IsUnique();

                    b.ToTable("ReceiverSignatures");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Serial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentDetailsId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SimId")
                        .HasColumnType("int");

                    b.Property<int?>("UsbId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentDetailsId");

                    b.HasIndex("SimId");

                    b.HasIndex("UsbId");

                    b.HasIndex("UserId");

                    b.ToTable("Serials");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.ServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ServiceProviders");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Sim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NetworkType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Sims");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Fees")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("NonEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("QuotaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SimId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UsbId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmpId");

                    b.HasIndex("NonEmployeeId");

                    b.HasIndex("QuotaId");

                    b.HasIndex("SimId");

                    b.HasIndex("UsbId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Usb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServiceProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("Usbs");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.UserOtp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.Branch", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedBy")
                        .WithMany("Branches")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.DeviceSerialOperation", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedBy")
                        .WithMany("DeviceSerialOperations")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Sim", "SIM")
                        .WithMany("DeviceSerialOperations")
                        .HasForeignKey("SimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("SIM");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.DocumentDetails", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.Document", "Document")
                        .WithMany("DocumentDetails")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Management.Models.ItemType", "ItemType")
                        .WithMany("DocumentDetails")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.InternetLine", b =>
                {
                    b.HasOne("Sim_Card_Management.Models.Branch", "Branch")
                        .WithMany("InternetLines")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedBy")
                        .WithMany("InternetLines")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Management.Models.PaymentType", "PaymentType")
                        .WithMany("InternetLines")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("InternetLines")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Management.Models.ServiceType", "ServiceType")
                        .WithMany("InternetLines")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Sim", "Sim")
                        .WithMany("InternetLines")
                        .HasForeignKey("SimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("CreatedBy");

                    b.Navigation("PaymentType");

                    b.Navigation("ServiceProvider");

                    b.Navigation("ServiceType");

                    b.Navigation("Sim");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.PaymentType", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedBy")
                        .WithMany("PaymentTypes")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.VpnConnection", b =>
                {
                    b.HasOne("Sim_Card_Management.Models.Branch", "Branch")
                        .WithMany("VpnConnections")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Management.Models.VpnConnectionType", "ConnectionType")
                        .WithMany("VpnConnections")
                        .HasForeignKey("ConnectionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedBy")
                        .WithMany("VpnConnections")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("VpnConnections")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ConnectionType");

                    b.Navigation("CreatedBy");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.VpnConnectionType", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedBy")
                        .WithMany("VpnConnectionTypes")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.AuditLog", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceStatus", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.Sim", "ReplacedBySim")
                        .WithMany()
                        .HasForeignKey("ReplacedBySimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.Usb", "ReplacedByUsb")
                        .WithMany()
                        .HasForeignKey("ReplacedByUsbId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.User", "ReportedByUser")
                        .WithMany("ReportedStatuses")
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Sim", "Sim")
                        .WithMany("DeviceStatuses")
                        .HasForeignKey("SimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Management.Models.DeviceStatusType", "StatusType")
                        .WithMany("DeviceStatuses")
                        .HasForeignKey("StatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Usb", "Usb")
                        .WithMany("DeviceStatuses")
                        .HasForeignKey("UsbId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReplacedBySim");

                    b.Navigation("ReplacedByUsb");

                    b.Navigation("ReportedByUser");

                    b.Navigation("Sim");

                    b.Navigation("StatusType");

                    b.Navigation("Usb");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceTransfer", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedByUser")
                        .WithMany("LoggedTransfers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Subscription", "FromSubscription")
                        .WithMany("DeviceTransfers")
                        .HasForeignKey("FromSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Subscription", "NewSubscription")
                        .WithMany()
                        .HasForeignKey("NewSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.Sim", "Sim")
                        .WithMany("DeviceTransfers")
                        .HasForeignKey("SimId");

                    b.HasOne("Sim_Card_Managment.Models.Employee", "ToEmployee")
                        .WithMany("ReceivedTransfers")
                        .HasForeignKey("ToEmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Usb", "Usb")
                        .WithMany("DeviceTransfers")
                        .HasForeignKey("UsbId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("FromSubscription");

                    b.Navigation("NewSubscription");

                    b.Navigation("Sim");

                    b.Navigation("ToEmployee");

                    b.Navigation("Usb");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Document", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumenttypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Documents")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedBy")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DocumentType");

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Employee", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("Sim_Card_Managment.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Group", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedBy")
                        .WithMany("UserCreatedGroups")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.GroupPermission", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.Group", "Group")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Quota", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Quotas")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.ReceiverSignature", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "SignedByUser")
                        .WithMany("Signatures")
                        .HasForeignKey("SignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Subscription", "Subscription")
                        .WithOne("ReceiverSignature")
                        .HasForeignKey("Sim_Card_Managment.Models.ReceiverSignature", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignedByUser");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Serial", b =>
                {
                    b.HasOne("Sim_Card_Management.Models.DocumentDetails", "DocumentDetails")
                        .WithMany("Serials")
                        .HasForeignKey("DocumentDetailsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Sim", "Sim")
                        .WithMany("Serials")
                        .HasForeignKey("SimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.Usb", "Usb")
                        .WithMany("Serials")
                        .HasForeignKey("UsbId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedBy")
                        .WithMany("Serials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DocumentDetails");

                    b.Navigation("Sim");

                    b.Navigation("Usb");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Sim", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Sims")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Subscription", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.DeviceAction", "Action")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedByUser")
                        .WithMany("CreatedSubscriptions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Employee", "Employee")
                        .WithMany("Subscriptions")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.NonEmployee", "NonEmployee")
                        .WithMany("Subscriptions")
                        .HasForeignKey("NonEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.Quota", "Quota")
                        .WithMany("Subscriptions")
                        .HasForeignKey("QuotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Sim", "Sim")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Usb", "Usb")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UsbId");

                    b.Navigation("Action");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");

                    b.Navigation("NonEmployee");

                    b.Navigation("Quota");

                    b.Navigation("Sim");

                    b.Navigation("Usb");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Usb", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.ServiceProvider", "ServiceProvider")
                        .WithMany("Usbs")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceProvider");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.User", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.Branch", b =>
                {
                    b.Navigation("InternetLines");

                    b.Navigation("VpnConnections");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.DeviceStatusType", b =>
                {
                    b.Navigation("DeviceStatuses");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.DocumentDetails", b =>
                {
                    b.Navigation("Serials");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.ItemType", b =>
                {
                    b.Navigation("DocumentDetails");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.PaymentType", b =>
                {
                    b.Navigation("InternetLines");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.ServiceType", b =>
                {
                    b.Navigation("InternetLines");
                });

            modelBuilder.Entity("Sim_Card_Management.Models.VpnConnectionType", b =>
                {
                    b.Navigation("VpnConnections");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceAction", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Document", b =>
                {
                    b.Navigation("DocumentDetails");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Employee", b =>
                {
                    b.Navigation("ReceivedTransfers");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Group", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.NonEmployee", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Permission", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Quota", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.ServiceProvider", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("InternetLines");

                    b.Navigation("Quotas");

                    b.Navigation("Sims");

                    b.Navigation("Usbs");

                    b.Navigation("VpnConnections");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Sim", b =>
                {
                    b.Navigation("DeviceSerialOperations");

                    b.Navigation("DeviceStatuses");

                    b.Navigation("DeviceTransfers");

                    b.Navigation("InternetLines");

                    b.Navigation("Serials");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Subscription", b =>
                {
                    b.Navigation("DeviceTransfers");

                    b.Navigation("ReceiverSignature");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Usb", b =>
                {
                    b.Navigation("DeviceStatuses");

                    b.Navigation("DeviceTransfers");

                    b.Navigation("Serials");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Branches");

                    b.Navigation("CreatedSubscriptions");

                    b.Navigation("DeviceSerialOperations");

                    b.Navigation("Documents");

                    b.Navigation("Employee");

                    b.Navigation("InternetLines");

                    b.Navigation("LoggedTransfers");

                    b.Navigation("PaymentTypes");

                    b.Navigation("ReportedStatuses");

                    b.Navigation("Serials");

                    b.Navigation("Signatures");

                    b.Navigation("UserCreatedGroups");

                    b.Navigation("VpnConnectionTypes");

                    b.Navigation("VpnConnections");
                });
#pragma warning restore 612, 618
        }
    }
}
