// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sim_Card_Managment.data;

#nullable disable

namespace Sim_Card_Managment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sim_Card_Managment.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PerformedBy");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ReplacedBySimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplacedByUsbId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("UsbId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedBySimId");

                    b.HasIndex("ReplacedByUsbId");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("SimId");

                    b.HasIndex("UsbId");

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NewSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("SimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToEmpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UsbId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FromSubscriptionId");

                    b.HasIndex("NewSubscriptionId");

                    b.HasIndex("SimId");

                    b.HasIndex("ToEmpId");

                    b.HasIndex("UsbId");

                    b.ToTable("DeviceTransfers");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NationalID")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.GroupPermission", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("GroupPermissions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.NonEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NonEmployees");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Quota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ExtraAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Period")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Quotas");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.ReceiverSignature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignatureData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SignedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SignedBy");

                    b.HasIndex("SubscriptionId")
                        .IsUnique();

                    b.ToTable("ReceiverSignatures");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Sim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Fees")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NetworkType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Sims");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EmpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NonEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("QuotaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UsbId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EmpId");

                    b.HasIndex("NonEmployeeId");

                    b.HasIndex("QuotaId");

                    b.HasIndex("SimId");

                    b.HasIndex("UsbId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Usb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Usbs");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.AuditLog", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "PerformedByUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PerformedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByUser");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceStatus", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.Sim", "ReplacedBySim")
                        .WithMany()
                        .HasForeignKey("ReplacedBySimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.Usb", "ReplacedByUsb")
                        .WithMany()
                        .HasForeignKey("ReplacedByUsbId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.User", "ReportedByUser")
                        .WithMany("ReportedStatuses")
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Sim", "Sim")
                        .WithMany("DeviceStatuses")
                        .HasForeignKey("SimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.Usb", "Usb")
                        .WithMany("DeviceStatuses")
                        .HasForeignKey("UsbId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReplacedBySim");

                    b.Navigation("ReplacedByUsb");

                    b.Navigation("ReportedByUser");

                    b.Navigation("Sim");

                    b.Navigation("Usb");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceTransfer", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedByUser")
                        .WithMany("LoggedTransfers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Subscription", "FromSubscription")
                        .WithMany("DeviceTransfers")
                        .HasForeignKey("FromSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Subscription", "NewSubscription")
                        .WithMany()
                        .HasForeignKey("NewSubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.Sim", "Sim")
                        .WithMany("DeviceTransfers")
                        .HasForeignKey("SimId");

                    b.HasOne("Sim_Card_Managment.Models.Employee", "ToEmployee")
                        .WithMany("ReceivedTransfers")
                        .HasForeignKey("ToEmpId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Usb", "Usb")
                        .WithMany("DeviceTransfers")
                        .HasForeignKey("UsbId");

                    b.Navigation("CreatedByUser");

                    b.Navigation("FromSubscription");

                    b.Navigation("NewSubscription");

                    b.Navigation("Sim");

                    b.Navigation("ToEmployee");

                    b.Navigation("Usb");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Employee", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("Sim_Card_Managment.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.GroupPermission", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.Group", "Group")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Permission", "Permission")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.ReceiverSignature", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.User", "SignedByUser")
                        .WithMany("Signatures")
                        .HasForeignKey("SignedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Subscription", "Subscription")
                        .WithOne("ReceiverSignature")
                        .HasForeignKey("Sim_Card_Managment.Models.ReceiverSignature", "SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SignedByUser");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Subscription", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.DeviceAction", "Action")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.User", "CreatedByUser")
                        .WithMany("CreatedSubscriptions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Employee", "Employee")
                        .WithMany("Subscriptions")
                        .HasForeignKey("EmpId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.NonEmployee", "NonEmployee")
                        .WithMany("Subscriptions")
                        .HasForeignKey("NonEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sim_Card_Managment.Models.Quota", "Quota")
                        .WithMany("Subscriptions")
                        .HasForeignKey("QuotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Sim", "Sim")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sim_Card_Managment.Models.Usb", "Usb")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UsbId");

                    b.Navigation("Action");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Employee");

                    b.Navigation("NonEmployee");

                    b.Navigation("Quota");

                    b.Navigation("Sim");

                    b.Navigation("Usb");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.User", b =>
                {
                    b.HasOne("Sim_Card_Managment.Models.Group", "Group")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.DeviceAction", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Employee", b =>
                {
                    b.Navigation("ReceivedTransfers");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Group", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.NonEmployee", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Permission", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Quota", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Sim", b =>
                {
                    b.Navigation("DeviceStatuses");

                    b.Navigation("DeviceTransfers");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Subscription", b =>
                {
                    b.Navigation("DeviceTransfers");

                    b.Navigation("ReceiverSignature");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.Usb", b =>
                {
                    b.Navigation("DeviceStatuses");

                    b.Navigation("DeviceTransfers");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Sim_Card_Managment.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedSubscriptions");

                    b.Navigation("Employee");

                    b.Navigation("LoggedTransfers");

                    b.Navigation("ReportedStatuses");

                    b.Navigation("Signatures");
                });
#pragma warning restore 612, 618
        }
    }
}
